// source/component/form/input/input-checkbox.jsx
import typo from '../typo.js'


const toggle = (id) => {
  const checkbox = document.getElementsByName(id)[0]

  if (checkbox !== undefined)
    checkbox.checked = ! checkbox.checked
}

export default ({ id, label, state, checked }) =>
    <label for={id} data-for-checkbox onClick={(e) => {
      e.stopPropagation();
      toggle(id)
    }}>
      <input
          type='checkbox'
          name={id}
          checked={state ==='checked'}
          data-default-state={state ==='checked'}
          value={checked}
          onClick={(e) => e.stopPropagation()} />
      <div>{typo(label)}</div>
    </label>

// source/component/form/input/input-checkbox.vue
<template>

  <label
      :for="requisite.id"
      data-for-checkbox
      @click.stop="toggle">
    
    <input
        type="checkbox"
        :name="requisite.id"
        :checked="checked"
        :data-default-state="requisite.state === 'checked' "
        :value="requisite.checked"
        @click.stop=""/>

    <div>{{ typo(requisite.label) }}</div>

  </label>

</template>


<script setup>
import { ref } from 'vue'

import typo from '../typo.js'


const props = defineProps({
  requisite: {
    type: Object,
    required: true
  }
})

const checked = ref(props.requisite.state === 'checked')

const toggle = () => checked = !checked
</script>
